using System.Linq;
using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;

public class SelectorController : MonoBehaviour
{
    // [SerializeField] private Text textInformation;
    [SerializeField] private TextMeshProUGUI textScrollSpeed;

    // ï¿½tï¿½Hï¿½[ï¿½}ï¿½bï¿½gï¿½wï¿½è•¶ï¿½ï¿½ï¿½ï¿½
    // private string informationTextFormat;
    private string scrollSpeedTextFormat;

    // ï¿½Xï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½x

    private GameObject tableViewObject;

    private SongItemTableViewController tableViewController;

    // BMSï¿½tï¿½@ï¿½Cï¿½ï¿½ï¿½ê——
    private BmsData selectedBmsData;

    // ï¿½Iï¿½ğ’†‚Ì•ï¿½ï¿½ï¿½ID
    private int selectedIndex = 0;

    // ï¿½ï¿½ï¿½Ê‚Ìï¿½
    private int beatmapCount;


    // Start is called before the first frame update
    void Start()
    {
        selectedBmsData = BmsDataCenter.CachedBmsDataList[selectedIndex];
        beatmapCount = BmsDataCenter.CachedBmsDataList.Count();

        scrollSpeedTextFormat = textScrollSpeed.text;
        ChangeScrollSpeed(BmsDataCenter.ScrollSpeed);
        tableViewObject = GameObject.Find("Table View");
        tableViewController = tableViewObject.GetComponent<SongItemTableViewController>();
        tableViewController.LoadData(BmsDataCenter.CachedBmsDataList);
    }



    // Update is called once per frame
    void Update()
    {
        // ï¿½Xï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ÏX
        if (Input.GetKeyDown(KeyCode.UpArrow))
        {
            ChangeScrollSpeed(BmsDataCenter.ScrollSpeed + 0.1f);
        }
        if (Input.GetKeyDown(KeyCode.DownArrow))
        {
            ChangeScrollSpeed(BmsDataCenter.ScrollSpeed - 0.1f);
        }

        // ï¿½ï¿½ï¿½èˆï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Space))
        {
            PlayerController.ScrollSpeed = BmsDataCenter.ScrollSpeed;
            PlayerController.BmsData = BmsDataCenter.CachedBmsDataList[tableViewController.SelectedIndex];
            SceneManager.LoadScene("PlayScene");
        }
        if (Input.GetKeyDown(KeyCode.Escape))
        {
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#elif UNITY_STANDALONE
            UnityEngine.Application.Quit();
#endif
        }
    }

    private void ChangeScrollSpeed(float newScrollSpeed)
    {
        BmsDataCenter.ScrollSpeed = Mathf.Clamp(newScrollSpeed, 0.1f, 10f);

        var text = string.Format(scrollSpeedTextFormat, BmsDataCenter.ScrollSpeed);
        textScrollSpeed.text = text;
    }
}
